### ISSUE TITLE
Not safely reading in table column names that conflict with ruby reserved words.

### ISSUE THREAD

**Issue by naturalethic** [Pistos/m4dbi#1]
I had a table with a column named 'class'.  The library overwrote the objects 'class' property (which should refer to its class object) with the value in my table column.  I discovered this because the traits additions refer to object.class for its operation, and was failing as it was the string result from my database column, rather than the object class. :)

**Comment by Pistos** [comment]
Thanks for reporting this, and thanks for trying M4DBI.  :)  I'll have to think about what I want to do about the general problem of colliding method names.  If you had any suggestions yourself, I'm open to hearing them.

**Comment by Pistos** [comment]
For the time being, I have decided I will respect any existing methods on the class, and provide an alternate means of accessing the column.  One or both of: my_model[ 'class' ], my_model.class_

**Comment by Pistos** [comment]
I have pushed changes to the master branch.  I have not released it officially yet.  Could you give it a try with your code, and/or provide me with a minimal code example that fails with 0.6.2?

**Comment by naturalethic** [comment]
Looking at your unit tests, it seems the best default test setup would be an in-memory sqlite3 db.  Shall I go ahead and modify the specs for that?  Then I'll throw in a test against a few keywords and other known default object properties (including class).

**Comment by naturalethic** [comment]
Oh, and I like the object['class'] means of referencing the column.  I'm finding this handy anyway as I override some property accessors on my model objects but still need to refer to the underlying column value.

**Comment by Pistos** [comment]
Feel free to fork and add in spec code that tests with in-memory SQLite3.  At the moment, I have ways to test PostgreSQL, MySQL and SQLite3 (file).  I look forward to your contribution(s).  Thanks for your time and interest.  :)

**Comment by Pistos** [comment]
Marking this issue closed.  Current HEAD of master branch fixes this issue.
