### ISSUE TITLE
Integer columns returned as strings

### ISSUE THREAD

**Issue by naturalethic** [Pistos/m4dbi#2]
I know this is probably an issue in DBI, and may even qualify as an enhancement.  At any rate, I think integer columns should be cast as ruby integers.

**Comment by Pistos** [comment]
They definitely are with PostgreSQL and SQLite3.  Are you getting Strings when using MySQL?  Or perhaps you can provide some sample code which demonstrates the problem.

**Comment by naturalethic** [comment]
Yeah, I'm on MySQL.  I now recall that this is a mysql-ruby problem and why I've chosen other drivers in the past.  I'll dig into that to see what's going on.  Would it be worth adding some unit tests to check type?

**Comment by Pistos** [comment]
If you could uncover more details, that would be awesome.  It's stumped me and Erik H (Ruby DBI lead) up to now.  There's no need to add extra tests, because the current spec suite fails with MySQL for this very reason.  :)

**Comment by naturalethic** [comment]
Bug in dbd-mysql -- here's the patch:

```
diff --git a/lib/dbd/mysql/database.rb b/lib/dbd/mysql/database.rb
index 2c4ab91..46c7e8b 100644
--- a/lib/dbd/mysql/database.rb
+++ b/lib/dbd/mysql/database.rb
@@ -60,7 +60,7 @@ module DBI::DBD::Mysql
         ::Mysql::Field.constants.grep(/^TYPE_/).each do |const|
         mysql_type = MysqlField.const_get(const)  # numeric type code
             coercion_method = DBI::Type::Varchar                 # default coercion method
-            case const
+            case const.to_s
             when 'TYPE_TINY'
                 mysql_type_name = 'TINYINT'
                 coercion_method = DBI::Type::Integer
@@ -111,7 +111,7 @@ module DBI::DBD::Mysql
                  'TYPE_SET',
                  'TYPE_BIT',
                  'TYPE_NULL'
-                mysql_type_name = const.sub(/^TYPE_/, '')
+                mysql_type_name = const.to_s.sub(/^TYPE_/, '')
             else
                 mysql_type_name = 'UNKNOWN'
             end
```

**Comment by Pistos** [comment]
Awesome.  I'll check this out as soon as I can, see if I can verify that it fixes the problem (i.e. gets the spec suite to pass).  I've also notified Erik.

**Comment by naturalethic** [comment]
Any news on this?

**Comment by Pistos** [comment]
Sorry, slipped out of mind.  Thanks for the keep-alive.  :)  I haven't gotten around to it yet, but I would like to soon.  I'll respond here afterwards.

**Comment by Pistos** [comment]
Okay, I applied your patch, and all M4DBI tests pass once again with the MySQL adapter.  :)  Thank you!  Let's see if Erik accepts the patch into DBI core.

**Comment by Pistos** [comment]
Erik accepted your patch: http://github.com/erikh/ruby-dbi/commit/750138abb79cf8dbe43695525b5a54081b55aa4b
