### ISSUE TITLE
Row level caching

### ISSUE THREAD

**Issue by naturalethic** [Pistos/m4dbi#3]
This:
    p MyModel[1]
    p MyModel[1]

Should result in this:
    #<MyModel:0x00000100b488f8 @row=[...]>
    #<MyModel:0x00000100b488f8 @row=[...]>
(same memory addresses)

Not this:
    #<MyModel:0x00000100b488f8 @row=[...]>
    #<MyModel:0x00000100b2ac68 @row=[...]>
(different memory addresses)

Agree, disagree?

**Comment by Pistos** [comment]
There shouldn't be any issues with equality and comparison.  c.f.:

  http://github.com/Pistos/m4dbi/blob/e3b73ec0d7f6e51945fb994a26723b691ce05064/spec/model.rb#L728-747

What benefits do you see from going the distance and actually using the same physical object in memory?  Memory savings?  Improved speed?  I think I'd want to see some convincing benchmarks.

**Comment by naturalethic** [comment]
I just want to keep from executing the same query over and over.  The app I'm working on uses a database that is read only.  It would be very convenient to be able to assume that all queries are deterministic.  I can implement this in my app instead of in your lib though.  If you want the code though, perhaps a feature that can be configured, I'd be happy to add it to the project.

**Comment by Pistos** [comment]
I think caching should be implemented at the application level.  If you can come up with a configurable or pluggable caching solution which is clean, simple, and not too heavy (LoC), I could consider it.  But, for example, if I were writing something against a read-only DB, I would put the caching in my app (as opposed to M4DBI).

**Comment by naturalethic** [comment]
Here's my solution for doing caching.  Let me know if you want to work on putting something like this in the library.

```
require 'digest'

module Deterministic
  def self.included(base)
    @@__cache__ = Hash.new

    def base.[](*args)
      digest = args.reduce(Digest::MD5.new << self.dbh.object_id.to_s << self.table.to_s) {|digest, arg| digest << arg.to_s }.hexdigest
      if not @@__cache__[digest]
        @@__cache__[digest] = super(*args)
      end
      @@__cache__[digest] 
    end
  end
end

class Unit < DBI::Model(:unit)
  include Deterministic
end
```

**Comment by naturalethic** [comment]
Here's a version that uses blocks for easier wrapping of the rest of the methods:

```
module Deterministic
  def self.included(base)
    @@__cache__ = Hash.new

    def base.__cache__(args)
      digest = args.reduce(Digest::MD5.new << self.dbh.object_id.to_s << self.table.to_s) {|digest, arg| digest << arg.to_s }.hexdigest
      if not @@__cache__[digest]
        @@__cache__[digest] = yield
      end
      @@__cache__[digest] 
    end

    def base.[](*args)
      __cache__(args) { super(*args) }
    end

    def base.s(*args)
      __cache__(args) { super(*args) }
    end
  end
end
```
